-- AlterTable
ALTER TABLE "Product" ADD COLUMN "platform" TEXT NOT NULL DEFAULT 'PC';
ALTER TABLE "Product" ADD COLUMN "region" TEXT NOT NULL DEFAULT 'EUROPA';
ALTER TABLE "Product" ADD COLUMN "storeLabel" TEXT NOT NULL DEFAULT 'Steam';
ALTER TABLE "Product" ADD COLUMN "cardSubtitle" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Product" ADD COLUMN "cashbackPercent" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Product" ADD COLUMN "likesCount" INTEGER NOT NULL DEFAULT 0;
